apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "nginx.fullname" . }}
  labels:
    {{- include "nginx.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}  # 사용할 복제본 수
  strategy:
    canary:
      maxSurge: "25%"  # 새로운 파드를 한 번에 생성할 수 있는 비율
      maxUnavailable: 0  # Canary 배포 중 사용할 수 없는 파드 수
      steps:
        - setWeight: 25  # Canary 배포 시, 새 버전으로 트래픽을 25%로 분산
        - pause: {duration: 10s}  # 10초 대기 후 다음 단계로 진행
        - setWeight: 50  # 새 버전으로 50% 트래픽 분산
        - pause: {duration: 10s}  # 10초 대기
        - setWeight: 75  # 새 버전으로 75% 트래픽 분산
        - pause: {duration: 10s}  # 10초 대기
        - setWeight: 100  # 전체 트래픽을 새 버전으로 전환
  revisionHistoryLimit: 2  # 롤백 가능한 이전 버전의 기록 수
  selector:
    matchLabels:
      {{- include "nginx.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nginx.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
