apiVersion: v1
data:
  config.yaml: "auth:\n  openid: {}\n  openshift:\n    client_id_prefix: kiali\n  strategy:
    anonymous\ndeployment:\n  accessible_namespaces:\n  - '**'\n  additional_service_yaml:
    {}\n  affinity:\n    node: {}\n    pod: {}\n    pod_anti: {}\n  configmap_annotations:
    {}\n  custom_secrets: []\n  host_aliases: []\n  hpa:\n    api_version: autoscaling/v2beta2\n
    \   spec: {}\n  image_digest: \"\"\n  image_name: quay.io/kiali/kiali\n  image_pull_policy:
    Always\n  image_pull_secrets: []\n  image_version: v1.50\n  ingress:\n    additional_labels:
    {}\n    class_name: nginx\n    override_yaml:\n      metadata: {}\n  ingress_enabled:
    false\n  instance_name: kiali\n  logger:\n    log_format: text\n    log_level:
    info\n    sampler_rate: \"1\"\n    time_field_format: 2006-01-02T15:04:05Z07:00\n
    \ namespace: istio-system\n  node_selector: {}\n  pod_annotations: {}\n  pod_labels:\n
    \   sidecar.istio.io/inject: \"false\"\n  priority_class_name: \"\"\n  replicas:
    1\n  resources:\n    limits:\n      memory: 1Gi\n    requests:\n      cpu: 10m\n
    \     memory: 64Mi\n  secret_name: kiali\n  service_annotations: {}\n  service_type:
    \"\"\n  tolerations: []\n  version_label: v1.50.0\n  view_only_mode: false\nexternal_services:\n
    \ custom_dashboards:\n    enabled: true\n  istio:\n    root_namespace: istio-system\n
    \ prometheus:\n    url: \"http://monitoring-prometheus-se-72057-100244919-aa32f1023424.kr.lb.naverncp.com:80\"\n  external_services:\n
    \ grafana:\n    url: \"http://grafana.monitoring:3000\"    \nidentity:\n  cert_file:
    \"\"\n  private_key_file: \"\"\nistio_namespace: istio-system\nkiali_feature_flags:\n
    \ certificates_information_indicators:\n    enabled: true\n    secrets:\n    -
    cacerts\n    - istio-ca-secret\n  clustering:\n    enabled: true\n  disabled_features:
    []\n  validations:\n    ignore:\n    - KIA1201\nlogin_token:\n  signing_key: CHANGEME00000000\nserver:\n
    \ metrics_enabled: true\n  metrics_port: 9090\n  port: 20001\n  web_root: /kiali\n"
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"config.yaml":"auth:\n  openid: {}\n  openshift:\n    client_id_prefix: kiali\n  strategy: anonymous\ndeployment:\n  accessible_namespaces:\n  - '**'\n  additional_service_yaml: {}\n  affinity:\n    node: {}\n    pod: {}\n    pod_anti: {}\n  configmap_annotations: {}\n  custom_secrets: []\n  host_aliases: []\n  hpa:\n    api_version: autoscaling/v2beta2\n    spec: {}\n  image_digest: \"\"\n  image_name: quay.io/kiali/kiali\n  image_pull_policy: Always\n  image_pull_secrets: []\n  image_version: v1.50\n  ingress:\n    additional_labels: {}\n    class_name: nginx\n    override_yaml:\n      metadata: {}\n  ingress_enabled: false\n  instance_name: kiali\n  logger:\n    log_format: text\n    log_level: info\n    sampler_rate: \"1\"\n    time_field_format: 2006-01-02T15:04:05Z07:00\n  namespace: istio-system\n  node_selector: {}\n  pod_annotations: {}\n  pod_labels:\n    sidecar.istio.io/inject: \"false\"\n  priority_class_name: \"\"\n  replicas: 1\n  resources:\n    limits:\n      memory: 1Gi\n    requests:\n      cpu: 10m\n      memory: 64Mi\n  secret_name: kiali\n  service_annotations: {}\n  service_type: \"\"\n  tolerations: []\n  version_label: v1.50.0\n  view_only_mode: false\nexternal_services:\n  prometheus:\n    enable: true\n    url: monitoring-prometheus-se-72057-100244919-aa32f1023424.kr.lb.naverncp.com\n  custom_dashboards:\n    enabled: true\n  istio:\n    root_namespace: istio-system\nidentity:\n  cert_file: \"\"\n  private_key_file: \"\"\nistio_namespace: istio-system\nkiali_feature_flags:\n  certificates_information_indicators:\n    enabled: true\n    secrets:\n    - cacerts\n    - istio-ca-secret\n  clustering:\n    enabled: true\n  disabled_features: []\n  validations:\n    ignore:\n    - KIA1201\nlogin_token:\n  signing_key: CHANGEME00000000\nserver:\n  metrics_enabled: true\n  metrics_port: 9090\n  port: 20001\n  web_root: /kiali\n"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app":"kiali","app.kubernetes.io/instance":"kiali","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"kiali","app.kubernetes.io/part-of":"kiali","app.kubernetes.io/version":"v1.50.0","helm.sh/chart":"kiali-server-1.50.0","version":"v1.50.0"},"name":"kiali","namespace":"istio-system"}}
  creationTimestamp: "2024-11-10T13:41:51Z"
  labels:
    app: kiali
    app.kubernetes.io/instance: kiali
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kiali
    app.kubernetes.io/part-of: kiali
    app.kubernetes.io/version: v1.50.0
    helm.sh/chart: kiali-server-1.50.0
    version: v1.50.0
  name: kiali
  namespace: istio-system
  resourceVersion: "23248814"
  uid: 6e18e6f5-9f58-44b4-954a-522b96d4e3d0
