apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    meta.helm.sh/release-name: kiali-release
    meta.helm.sh/release-namespace: istio-system
  labels:
    app: kiali
    app.kubernetes.io/instance: kiali
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kiali
    app.kubernetes.io/part-of: kiali
    app.kubernetes.io/version: v2.0.0
    helm.sh/chart: kiali-server-2.0.0
    version: v2.0.0
  name: kiali-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kiali  # ClusterRole을 'kiali'로 설정
subjects:
- kind: ServiceAccount
  name: kiali
  namespace: istio-system

