apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cicd-3tier
  namespace: argocd
spec:
  ignoreDifferences:
  - group: cilium.io
    kind: CiliumIdentity
  project: default
  source:
    repoURL: 'https://github.com/choejaehun/cicd-project.git'  
    targetRevision: HEAD
    targetRevision: 'main'
    path: cicd-3tier     
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
  sources:
    - repoURL: 'https://github.com/choejaehun/cicd-project.git'
      path: cicd-3tier/cicd-mysql
      targetRevision: HEAD
    - repoURL: 'https://github.com/choejaehun/cicd-project.git'
      path: cicd-3tier/cicd-nginx
      targetRevision: HEAD
    - repoURL: 'https://github.com/choejaehun/cicd-project.git'
      path: cicd-3tier/cicd-spring-boot
      targetRevision: HEAD
