apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cicd-mysql
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/choejaehun/cicd-project.git'
    targetRevision: HEAD
    path: cicd-3tier/cicd-mysql
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cicd-nginx
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/choejaehun/cicd-project.git'
    targetRevision: HEAD
    path: cicd-3tier/cicd-nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cicd-tomcat
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/choejaehun/cicd-project.git'
    targetRevision: HEAD
    path: cicd-3tier/cicd-tomcat
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
