FROM jenkins/jenkins:lts

USER root

RUN apt-get update && apt-get install -y openssh-client

RUN mkdir -p /root/.ssh && chmod 700 /root/.ssh

COPY /root/.ssh/authorized_keys /root/.ssh/authorized_keys
RUN chmod 600 /root/.ssh/authorized_keys


CMD ["bash"]
