version: '3'
services:
  jenkins:
    image: choijaehun/jenkins:latest
    container_name: jenkins_server
    privileged: true
    stdin_open: true
    tty: true
    restart: always
    ports:
      - "18080:8080"
      - "50000:50000"
    environment:
      TZ: "Asia/Seoul"
    networks:
      ci-network:
        ipv4_address: 192.168.100.10
    command: ["/usr/sbin/init"]
    cap_add:
      - SYS_ADMIN

  ansible:
    image: choijaehun/ansible:latest
    container_name: ansible-server
    privileged: true
    stdin_open: true
    tty: true
    restart: always
    ports:
      - "10022:22"
    environment:
      TZ: "Asia/Seoul"
    networks:
      ci-network:
        ipv4_address: 192.168.100.11
    command: ["/usr/sbin/init"]
    cap_add:
      - SYS_ADMIN

networks:
  ci-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24

volumes:
  jenkins_home:
