version: '3'
services:
  jenkins:
    image: choijaehun/jenkins:latest
    container_name: jenkins
    privileged: true
    stdin_open: true
    tty: true
    ports:
      - "18080:8080"
      - "50000:50000"
    environment:
      TZ: "Asia/Seoul"
    volumes:
      - jenkins_home:/var/jenkins_home

  ansible-server:
     image: choijaehun/ansible:latest
     container_name: ansible-server
     privileged: true
     ports:
       - "10022:22"
     environment:
       - container=docker
     volumes:
       - /sys/fs/cgroup:/sys/fs/cgroup
     command: /usr/sbin/init
     stdin_open: true  # -i 옵션에 해당
     tty: true  # -t 옵션에 해당

volumes:
  jenkins_home: