FROM jenkins/jenkins:lts

USER root

RUN yum install -y openssh-client

RUN mkdir -p /root/.ssh && chmod 700 /root/.ssh


COPY /root/.ssh/id_rsa /root/.ssh/id_rsa
COPY /root/.ssh/id_rsa.pub /root/.ssh/id_rsa.pub


RUN chmod 600 /root/.ssh/id_rsa && chmod 644 /root/.ssh/id_rsa.pub


CMD ["bash"]
