version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins_server
    privileged: true
    stdin_open: true
    tty: true
    restart: always
    ports:
      - "18080:8080"
      - "50000:50000"
    environment:
      TZ: "Asia/Seoul"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /root/.ssh:/root/.ssh:ro
    networks:
      - ci-network

  ansible:
    build: .
    container_name: ansible-server
    privileged: true
    stdin_open: true
    tty: true
    restart: always
    ports:
      - "10022:22"
    environment:
      TZ: "Asia/Seoul"
    volumes:
      - /root/.ssh:/root/.ssh:ro  # SSH 키를 마운트
    networks:
      - ci-network

networks:
  ci-network:
    driver: bridge

volumes:
  jenkins_home:
