apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJrOHMtcmVnaXN0cnkua3IubmNyLm50cnVzcy5jb20iOnsidXNlcm5hbWUiOiJuY3BfaWFtX0JQQVNLUjRUMzM5bGxXRVhYZnBKIiwicGFzc3dvcmQiOiJuY3BfaWFtX0JQS1NLUldTWWQ5eUp6UERLZndIQmxQMmpsU0dkVlZBaXIiLCJhdXRoIjoiYm1Od1gybGhiVjlDVUVGVFMxSTBWRE16T1d4c1YwVllXR1p3U2pwdVkzQmZhV0Z0WDBKUVMxTkxVbGRUV1dRNWVVcDZVRVJMWm5kSVFteFFNbXBzVTBka1ZsWkJhWEk9In19fQ==
kind: Secret
metadata:
  creationTimestamp: "2024-10-08T04:16:11Z"
  name: ncp-registry-secret
  namespace: cicd
  resourceVersion: "764887"
  uid: ef58f537-ef7b-4af8-8837-38458120dd6b
type: kubernetes.io/dockerconfigjson
