# Default values for order.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: k8s-registry.kr.ncr.ntruss.com/cicd/user
  tag: "1.0"
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.

# This is for the secretes for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: 
  - name: ncp-registry-secret
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: LoadBalancer
  port: 8080

ingress:
  enabled: false
    
resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

configmap:
  db-name: "cicd_project"
  db-url: "mysql"
  cache-url: "redis"

secret:
  password: "UEBzc3cwcmQ="
  username: "cm9vdAo="
