spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100

  sql:
    init:
      mode: always

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 20MB
      max-request-size: 20MB

server:
  port: 8080
