spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}
    username: root
    password: P@ssw0rd
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update # 주의: 프로덕션에서는 update나 validate로 설정
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100

  sql:
    init:
      mode: always

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 20MB
      max-request-size: 20MB

server:
  port: 8088
