spring:
  datasource:
    url: jdbc:mysql://${DB_URL}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
  main:
    allow-bean-definition-overriding: true
server:
  port: 8080
    allow-bean-definition-overriding: true
  data:
    redis:
      host: ${CACHE_URL}
      port: 6379
