pipeline {
    agent any

    tools {
        jdk 'jdk17'
    }

    environment {
        DOCKER_REGISTRY_CREDENTIALS = credentials('docker-hub-credentials')
        AUTHOR_IMAGE = "choijaehun/authors"
        IMAGE_TAG = "latest"
        MYSQL_HOST = '172.17.0.3'
        MYSQL_PORT = '3306'
        MYSQL_DATABASE = 'cicd_project'
    }

    stages {
        stage('Set New Tag') {
            steps {
                script {
                    // 새로운 Docker 태그를 계산하는 로직을 여기에 추가 (예: 기존 태그에서 0.01 증가)
                    // 예시: 아래와 같이 수동으로 설정하거나 동적으로 계산
                    env.NEW_TAG = "21" // 동적으로 계산한 값을 설정
                }
            }
        }
        stage('Checkout') {
            steps {
                git credentialsId: 'ssh-key', url: 'https://github.com/choejaehun/cicd-project.git', branch: 'main'
            }
        }
        

        stage('Set Permissions') {
            steps {
                sh 'chmod +x ./cicd-pipeline/author/gradlew'
            }
        }
        stage('Set Image Tag') {
            steps {
                script {
                    // Jenkins 빌드 번호로 태그 설정
                    IMAGE_TAG = "${BUILD_NUMBER}"
                    echo "빌드 번호로 설정된 태그: ${IMAGE_TAG}"
                }
            }
        }
        stage('Build Author') {
            steps {
                script {
                    echo "Author 프로젝트 빌드 실행:"
                    sh "./cicd-pipeline/author/gradlew -p ./cicd-pipeline/author clean build -x test -Dspring.datasource.url=jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE} -Dspring.datasource.username=root -Dspring.datasource.password=P@ssw0rd"
                }
            }
        }

        stage('Docker Build and Push Author') {
            steps {
                script {
                    def imageName = "${AUTHOR_IMAGE}:${IMAGE_TAG}"
                    docker.withRegistry('https://index.docker.io/v1/', 'docker-hub-credentials') {
                        def app = docker.build(imageName, './cicd-pipeline/author')
                        app.push("${IMAGE_TAG}")
                    }
                    sh "docker rmi ${imageName} || true" // 푸시 후 로컬에서 이미지 삭제
                }
            }
        }

        stage('Update Helm Values') {
            steps {
                script {
                    // values.yaml 파일에서 tag 값을 NEW_TAG로 업데이트
                    sh "sed -i 's/tag:.*/tag: \"${NEW_TAG}\"/' ./cicd-pipeline/author/values.yaml"
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}