apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "author.fullname" . }}-configmap
data:
  db-name: {{ index .Values.configmap "db-name" }}
  db-url: {{ index .Values.configmap "db-url" }}
  db-port: {{ .Values.configmap.db-port }}