apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "author.fullname" . }}-canary
  annotations:
    # ArgoCD Image Updater 설정 추가
    argocd-image-updater.argoproj.io/image-list: choijaehun/authors
    argocd-image-updater.argoproj.io/choijaehun/authors.update-strategy: latest
  labels:
    {{- include "author.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: { duration: 15s }
        - setWeight: 50
        - pause: { duration: 15s }
        - setWeight: 100
  selector:
    matchLabels:
      {{- include "author.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "author.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: author-configmap
                  key: db-port
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: author-configmap
                  key: db-url
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: author-configmap
                  key: db-name
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: author-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: author-secret
                  key: password
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
