apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: cicd
data:
  nginx.conf: |
    http {
      upstream user_service {
          server user-service.cicd.svc.cluster.local:80;
      }
      upstream author_service {
          server author-service.cicd.svc.cluster.local:80;
      }
      server {
          listen 80;
          location /users {
              proxy_pass http://user_service;
          }
          location /authors {
              proxy_pass http://author_service;
          }
      }
    }
