{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "nginx.fullname" . }}
  namespace: cicd
  labels:
    {{- include "nginx.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  rules:
    - http:
        paths:
          {{- range $index, $host := .Values.ingress.hosts }}
          {{- range $path := $host.paths }}
          - path: {{ $path.path | quote }}
            pathType: {{ $path.pathType | default "Prefix" }}
            backend:
              service:
                name: {{ $path.backend.serviceName }}
                namespace: {{ $path.backend.namespace | default "cicd" }}
                port:
                  number: {{ $path.backend.port.number | default 80 }}
          {{- end }}
          {{- end }}
{{- end }}
